[project]
name = "clotho"
version = "0.1.0"
description = "Your personal knowledge toolkit."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiofiles>=25.1.0", # Asynchronous file operations
    "loguru>=0.7.3", # Logging
    "playwright>=1.56.0", # Scraping and browser automation
    "trafilatura>=2.0.0", # HTML to markdown conversion
    "python-dotenv>=1.2.1", # Environment variable management
]

[dependency-groups]
dev = [
    "ruff>=0.14.5", # Linting / formatting
]


[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["clotho"]
